### ISSUE TITLE
SSL 证书过期

### ISSUE THREAD

**Issue by AGDholo** [notadd/docs#3]
docs.notadd.com 的管理员没有正确配置好此网站。为避免您的信息失窃，Firefox 并未与此网站建立连接。

此网站采用了 HTTP 严格传输安全（HSTS）机制，要求 Firefox 只能与其建立安全连接。正因如此，您也不能将此证书加入例外列表。

**Comment by zuohuadong** [comment]
已经修复，并使用ECC证书～ 感谢
